config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products

  resource :cart, only: [ :show ] do
    post "add", path: "add/:id"
    get :checkout
  end
  resources :orders, only: [:index, :show, :create]
  resources :users

  root 'products#index'

  get 'product/orders'
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart
  attr_reader :items

  def self.build_from_hash hash
    items = if hash["cart"] then
       hash["cart"]["items"].map do |item_data|
     CartItem.new item_data["product_id"], item_data["quantity"]
    end
    else
      []
    end
    new items
  end 

  def initialize items = []
    @items = items
  end

  def add_item product_id
    item = @items.find {|item| item.product_id == product_id}

      if item
       item.increment
      else
       @items << CartItem.new(product_id)
      end
   end

   def empty?
     @items.empty?
   end

   def count
     @items.length
   end

    def serialize
      @items = @items.map do |item|

      {
         "product_id" => item.product_id,
         "quantity" => item.quantity
      }
      end
      {
       
      "items" => items

      }
   end
   
   def total_price
       @items.inject(0) { |sum, item| sum + item.total_price}
   end
end

app/models/cart_item.rb
class CartItem
  attr_reader :product_id, :quantity

  def initialize product_id, quantity = 1
    @product_id = product_id
    @quantity = quantity
  end
  
  def increment
    @endquantity = @quantity + 1
  end

  def product
    Product.find product_id
  end


  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
end

app/models/order_form.rb
class OrderForm
  include ActiveModel::Model

  attr_accessor :user, :order
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  validates_presence_of :name, :price, :description, :size_type, :brand
  validates_numericality_of :price

  def self.search(search)
      if search
         where(["name LIKE ?", "%#{search}%"])
      else
	 all
      end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
  

 def initialize_cart
   @cart = Cart.build_from_hash session
 end

 def authenticate_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: "you are not permit to perform this operation"
   end
 end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :initialize_cart

  def add
    @cart.add_item params[:id]
    session["cart"] = @cart.serialize
    product = Product.find params[:id]
    redirect_to :back, notice: "Added #{product.name} to cart."
  end

  def show
  end

  def checkout
    @order_form = OrderForm.new user: User.new
  end 
end

app/controllers/products_controller.rb
require 'product_decorator'

class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :initialize_cart
  before_action :authenticate_admin!, only: [:new, :edit, :update, :create, :destroy]
  
  layout "products"
  # GET /products
  # GET /products.json
  def index
    @products = Product.search(params[:search])
  end

  # GET /products/1
  # GET /products/1.json
  def show
    render layout: "application"
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new()

    @product.name = params[:product][:name] 
    
    @product.image = params[:product][:image]
    @product.size_type = params[:product][:size_type]
    @product.brand = params[:product][:brand]

    #create an instance/object of a BasicProduct
    
    myProduct = BasicProduct.new(10, @product.brand )

    #add the extra features to the new product
    if params[:product][:trailers].to_s.length > 0 then
      myProduct = TrailersDecorator.new(myProduct)
    end

   # populate the price and the description details
   @product.price = myProduct.price
   @product.description = myProduct.details

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :image, :description, :size_type, :brand)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/application/_cart.html.haml
-if @cart
 %p.navbar-text.navbar-right
  -if @cart.empty?  
   Your cart is empty.
  -else
   =link_to "You have #{pluralize @cart.count, "item"}.", cart_path
   
  
 
   

app/views/application/_nav.html.erb
<!DOCTYPE html>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="logo" href="#">Clontarf rent store</a>
      	
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Products", products_path %></li>
     
       
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
   
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Admin</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
	<p class="navbar-text navbar-right">
		
	  <% if user_signed_in? %>
	    Logged in as <%= current_user.email %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
	  <% else %>
	    <%= link_to "Login", new_user_session_path, class: "navbar-link" %>
	  <% end %>
		
	</p>
       <%= render "cart" %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/carts/checkout.html.haml
%h1 Checkout

%h2 Yoy are checking out for booking bike

%ul
  -@cart.items.each do |item|
    %li
      =item.quantity
      =item.product.name
      =item.total_price
      
%p
  %strong
  Total price:
  =@cart.total_price

=form_for @order_form, url: orders_path do |f|
  =f.fields_for :user, @order_form.user do |u|
    .form-group
      %p=u.text_field :name, placeholder: "Name", class: "form-control input-lg"
      %p
        =u.text_field :email, placeholder: "Email", class: "form-control"
    .form-group
      .row
        %p.col-md-6=u.text_field :address, placeholder: "Address", class: "form-control"
        %p.col-md-6=u.text_field :name, placeholder: "Postal code", class: "form-control"
        %p.col-md-6=u.text_field :name, placeholder: "City", class: "form-control"
      %p=u.country_select :country, {priority_countries: ["GB", "US", "ES", "PT"]}, {class: "form-control"}

app/views/carts/show.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Quantity
      %th Product
      %th Price

  -@cart.items.each do |item|
    %tr
      %td=item.quantity
      %td
        
        =link_to item.product.name, item.product
      %td=item.total_price
  %tfoot
    %tr
      %td.text-right
        %strong
          Total:
          =@cart.total_price

%p=link_to "Checkout", checkout_cart_path, class: "btn btn-primary"

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>
<head>
  <title>RailsStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>




	<%= render "nav" %>
	
 	<div id="container">
	  <%= yield %>
	</div>

	<div style="clear:both">&nbsp;</div>

	<div id="footer">
	 <h6 class="footertext">&copy; Clontarf rent bike store; 2016</h6>
	</div>


</body>
</html>

app/views/layouts/products.html.erb
<!DOCTYPE html>


<html>
<head>
  <title>RailsStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



	<%= render "nav" %>
	
 <div id="container">
	<div id="container-products">
	  	
	  <%= content_tag :div, notice, class: "bg-success" %>
	  <%= content_tag :div, alert, class: "bg-danger" %>
	  <%= yield %>
	</div>



	<div id="sidebar">
		<h2>sidebar</h2>
		<aside id="text-6" class="widget widget_text"><h3 class="widget-title">Our Prices</h3>			
			<div class="textwidget">
				<strong>Standard Bikes</strong>
				1 hr – €5<br>
				3 hours – €10<br>
				Full Day – €15<br><br>
				<strong>Tandem &amp; Electric Bikes</strong><br>
				€10 for 1 hour<br>
				€20 for 3 hours<br>
				€30 for full Day<br><br>
				<strong>Carry Along for Kids</strong><br>
				From €2.50 for Child’s Seat<br><br>
				<strong>Trailers (Fits up to 2 kids)</strong><br>
				From €10
			</div>
		</aside>			
	</div>
		

		
	<div style="clear:both">&nbsp;</diV>
 </div>
<div id="footer">
		<h6 class="footertext">&copy; Clontarf rent bike store; 2016</h6>
	</div>


</body>
</html>

app/views/products/_form.html.haml
= form_for @product, multipart: true  do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :image
    = f.file_field :image
  .field
    = f.label :size
    = f.text_field :size_type
   
   
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :brand
    = f.text_field :brand
  .field
    = f.label :trailers
    = check_box_tag 'product[trailers]', 'trailers'
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products

= form_tag products_path, method: 'get' do 
  = text_field_tag :search, params[:search]
  = submit_tag "Search" 

%table.table.table-hover
  %thead    
  %tr
  %th Name
  %th Price
  %th Image
  %th Description
  %th Size
  %th Brand
  %th



    - @products.each do |product|
      %tr
        %td= link_to product.name, product
        %td= product.price
        %td= image_tag product.image.thumb
        %td= product.description
        %td= product.size_type
        %td= product.brand
        %td
          -if current_user && current_user.admin?
            = link_to 'Edit', edit_product_path(product)
            = link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }


	

%br
-if current_user && current_user.admin?
  %p= link_to 'New Product', new_product_path, class: "btn btn-primary"

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

 
%h1= @product.name

%p= @product.price
%p= image_tag @product.image, height: "300%"


%p=link_to "Add bike for booking", add_cart_path, method: :post, class: "btn btn-primary"
 
%p
  %b Description:
  = @product.description
%p
  %b Brand:
  = @product.brand
%p
  %b Size:
  = @product.size_type 
= link_to 'Back', products_path
\|
-if current_user && current_user.admin?
  = link_to 'Edit', edit_product_path(@product)
  
  